image: python:3.9

stages:
  - test
  - build
  - deploy

test:
  stage: test
  before_script:
    - apt update
    - apt-get install -y build-essential
    - pip install -r requirements.txt
    - pip install -e .
  script:
    - python run_unit_tests.py

wheel-linux:
  stage: build
  before_script:
    - apt update
    - apt-get install -y build-essential
    - mkdir wheel/
  script:
    - pip wheel -v . --wheel-dir wheel/
