image: python:3.9

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - apt update
  - apt-get install -y build-essential octave
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate

Build Package:
  stage: build
  artifacts:
    paths:
      - dist/*.whl
  script:
    - pip install -r requirements.txt
    - python setup.py bdist_wheel
    - pip install dist/hermespy-3.0.0-py3-none-any.whl[test, quadriga, documentation]

Unit Testing:
  stage: test
  dependencies:
    - Build Package
  script:
    - python -m unittest discover tests/unit_tests

Integration Testing:
  stage: test
  dependencies:
    - Build Package
  script:
    - python -m unittest discover tests/integration_tests

Integrity Testing:
  stage: test
  dependencies:
    - Build Package
  script:
    - python -m unittest discover tests/integrity_tests

pages:
  stage: deploy
  only:
    - master
  script:
    - python -m setup build_sphinx
  after_script:
    - mkdir public/
    - cp -r documentation/html/* public/
  artifacts:
    paths:
      - public
