image: python:3.9

stages:
  - build
  - test
  - deploy

Build Package:
  stage: build
  artifacts:
    paths:
      - env/
  before_script:
    - apt update
    - apt-get install -y build-essential octave
  script:
    - python -m venv env/
    - source env/bin/activate
    - pip install .[quadriga]

Unit Testing:
  stage: test
  dependencies:
    - Build Package
  before_script:
    - apt update
    - apt-get install -y octave
    - source env/bin/activate
  script:
    - python -m unittest discover tests/unit_tests

Integration Testing:
  stage: test
  dependencies:
    - Build Package
  before_script:
    - apt update
    - apt-get install -y octave
    - source env/bin/activate
  script:
    - python -m unittest discover tests/integration_tests

Integrity Testing:
  stage: test
  dependencies:
    - Build Package
  before_script:
    - apt update
    - apt-get install -y octave
    - source env/bin/activate
  script:
    - python -m unittest discover tests/integrity_tests

pages:
  stage: deploy
  only:
    - master
  before_script:
    - apt update
    - apt-get install -y build-essential octave
    - pip install -e .[quadriga]
    - pip install -r requirements_doc.txt
  script:
    - python -m setup build_sphinx
  after_script:
    - mkdir public/
    - cp -r documentation/html/* public/
  artifacts:
    paths:
      - public
