image: python:3.9

stages:
  - test
  - build
  - deploy

test:
  stage: test
  before_script:
    - apt update
    - apt-get install -y build-essential octave
    - pip install .[quadriga]
  script:
    - python -m unittest discover tests/unit_tests

wheel-linux:
  stage: build
  only:
    - master
  before_script:
    - apt update
    - apt-get install -y build-essential
    - mkdir wheel/
  script:
    - pip wheel -v . --wheel-dir wheel/

pages:
  stage: deploy
  only:
    - master
  before_script:
    - apt update
    - apt-get install -y build-essential octave
    - pip install -e .[quadriga]
    - pip install -r requirements_doc.txt
  script:
    - python -m setup build_sphinx
  after_script:
    - mkdir public/
    - cp -r documentation/html/* public/
  artifacts:
    paths:
      - public
