image: python:3.7

before_script:
  - apt update
  - apt-get install -y build-essential
  - pip install -r requirements.txt
  - pip install .

test:
  stage: test
  script:
    - python run_unit_tests.py
