image: python:3.7

stages:
  - test
  - build

test:
  stage: test
  before_script:
    - apt update
    - apt-get install -y build-essential
    - pip install -r requirements.txt
    - pip install .
  script:
    - python run_unit_tests.py

wheel-linux:
  stage: build
  before_script:
    - apt-get install -y build-essential
    - mkdir wheels/
  script:
    - pip wheel -v . --wheel-dir wheels/
  artifacts:
    paths:
      - wheels
