image: python:3.9

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  GIT_SUBMODULE_STRATEGY: recursive
  
stages:
  - build
  - test
  - deploy

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - apt update
  - apt-get install -y build-essential octave pandoc
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate

Build Package:
  stage: build
  script:
    - export MAKEFLAGS="-j $(grep -c ^processor /proc/cpuinfo)"
    - pip install .[test,quadriga,documentation,uhd,audio]

Unit Testing:
  stage: test
  dependencies:
    - Build Package
  script:
    - python tests/test_install.py unit_tests

Integration Testing:
  stage: test
  dependencies:
    - Build Package
  script:
    - python tests/test_install.py integration_tests

Integrity Testing:
  stage: test
  dependencies:
    - Build Package
  script:
    - python tests/test_install.py integrity_tests

pages:
  stage: deploy
  only:
    - master
  script:
    - python -m setup build_sphinx
  after_script:
    - mkdir public/
    - cp -r documentation/html/* public/
  artifacts:
    paths:
      - public
