[bumpver]

current_version = "1.2.0"
version_pattern = "MAJOR.MINOR.PATCH"
commit_message = "Bump to version {new_version}"
commit = false
tag = false
push = false

[bumpver.file_patterns]

# Root directory files
"README.md" = [ "{version}" ]
"bumpver.toml" = [ 'current_version = "{version}"' ]
"setup.py" = [ '__version__ = "{version}"' ]
".gitlab-ci.yml" = [ 'HERMES_VERSION: "{version}"' ]

# Source files
"hermespy/*/*.py" = [ '__version__ = "{version}"' ]

# Test files
"tests/*/*.py" = [ '__version__ = "{version}"' ]
"tests/test_install.py" = [ '__version__ = "{version}"' ]