[bumpver]

current_version = "0.2.7"
version_pattern = "MAJOR.MINOR.PATCH"
commit_message = "Bumb to version {new_version}"
commit = false
tag = false
push = false

[bumpver.file_patterns]

# Root directory files
"README.md" = [ "{version}" ]
"bumpver.toml" = [ 'current_version = "{version}"' ]
"setup.py" = [ 'version="{version}"', "'version': ('setup.py', '{version}')" ]

# Source files
"hermespy/bin/*.py" = [ '__version__ = "{version}"' ]
"hermespy/channel/*.py" = [ '__version__ = "{version}"' ]
"hermespy/coding/*.py" = [ '__version__ = "{version}"' ]
"hermespy/core/*.py" = [ '__version__ = "{version}"' ]
"hermespy/core/tools/*.py" = [ '__version__ = "{version}"' ]
"hermespy/hardware_loop/*.py" = [ '__version__ = "{version}"' ]
"hermespy/modem/*.py" = [ '__version__ = "{version}"' ]
"hermespy/modem/tools/*.py" = [ '__version__ = "{version}"' ]
"hermespy/precoding/*.py" = [ '__version__ = "{version}"' ]
"hermespy/radar/*.py" = [ '__version__ = "{version}"' ]
"hermespy/simulation/*.py" = [ '__version__ = "{version}"' ]
"hermespy/simulation/noise/*.py" = [ '__version__ = "{version}"' ]
"hermespy/simulation/rf_chain/*.py" = [ '__version__ = "{version}"' ]
"hermespy/tools/*.py" = [ '__version__ = "{version}"' ]

# ToDo: Test files
