[bumpver]

current_version = "0.1.0"
version_pattern = "MAJOR.MINOR.PATCH"
commit_message = "Bumb to version {new_version}"
commit = false
tag = false
push = false

[bumpver.file_patterns]

# Root directory files
"README.md" = [ "{version}" ]
"bumpver.toml" = [ 'current_version = "{version}"' ]
"setup.py" = [ 'version="{version}"' ]

# Source files
"bin/*.py" = [ '__version__ = "{version}"' ]
"channel/*.py" = [ '__version__ = "{version}"' ]
"coding/*.py" = [ '__version__ = "{version}"' ]
"modem/*.py" = [ '__version__ = "{version}"' ]
"modem/precoding/*.py" = [ '__version__ = "{version}"' ]
"modem/rf_chain_models/*.py" = [ '__version__ = "{version}"' ]
"modem/tools/*.py" = [ '__version__ = "{version}"' ]
"noise/*.py" = [ '__version__ = "{version}"' ]
"scenario/*.py" = [ '__version__ = "{version}"' ]
"simulator_core/*.py" = [ '__version__ = "{version}"' ]
"simulator_core/tools/*.py" = [ '__version__ = "{version}"' ]
"source/*.py" = [ '__version__ = "{version}"' ]

# ToDo: Test files
