[build-system]
requires = [
    "setuptools>=42",
    "sphinx",
    "wheel",
    "pybind11",
    "scikit-build",
    "cmake"
]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 400
target-version = ['py39']