# -*- coding: utf-8 -*-
from .animation import Trajectory, LinearTrajectory, StaticTrajectory
from .antennas import (
    SimulatedAntenna,
    SimulatedCustomArray,
    SimulatedAntennaArray,
    SimulatedDipole,
    SimulatedIdealAntenna,
    SimulatedLinearAntenna,
    SimulatedPatchAntenna,
    SimulatedUniformArray,
)
from .beamforming import DeviceFocus
from .drop import SimulatedDrop
from .evaluators import SidelobeEvaluator, SI, SSINR
from .rf import (
    ADC,
    DAC,
    Gain,
    AutomaticGainControl,
    QuantizerType,
    GainControlType,
    PowerAmplifier,
    SalehPowerAmplifier,
    RappPowerAmplifier,
    ClippingPowerAmplifier,
    CustomPowerAmplifier,
    HPF,
    MixerType,
    IdealMixer,
    Mixer,
    RampGenerator,
    Shift,
    Source,
    Split,
    Sum,
    X4,
    NoiseLevel,
    N0,
    ThermalNoise,
    SNR,
    NoiseModel,
    NoiseRealization,
    AWGN,
    AWGNRealization,
    PhaseNoise,
    PhaseNoiseRealization,
    NoPhaseNoise,
    OscillatorPhaseNoise,
    RFBlock,
    RFBlockRealization,
    RFBlockPort,
    RFBlockPortType,
    RFChain,
    RFChainRealization,
    RFBlockReference,
    RFSignal,
)
from .scenario import SimulationScenario
from .simulation import Simulation
from .simulated_device import (
    SimulatedDeviceState,
    ProcessedSimulatedDeviceInput,
    SimulatedDevice,
    SimulatedDeviceOutput,
    SimulatedDeviceReceiveRealization,
    SimulatedDeviceTransmission,
    SimulatedDeviceReception,
    TriggerModel,
    TriggerRealization,
    RandomTrigger,
    StaticTrigger,
    SampleOffsetTrigger,
    TimeOffsetTrigger,
)
from .isolation import Isolation, SpecificIsolation, PerfectIsolation, SelectiveLeakage
from .coupling import Coupling, ImpedanceCoupling, PerfectCoupling
from .modem import (
    SCIdealChannelEstimation,
    SingleCarrierIdealChannelEstimation,
    OFDMIdealChannelEstimation,
    EBN0,
    ESN0,
)

__author__ = "Jan Adler"
__copyright__ = "Copyright 2025, Barkhausen Institut gGmbH"
__credits__ = ["Jan Adler"]
__license__ = "AGPLv3"
__version__ = "1.5.0"
__maintainer__ = "Jan Adler"
__email__ = "jan.adler@barkhauseninstitut.org"
__status__ = "Prototype"


__all__ = [
    "Trajectory",
    "LinearTrajectory",
    "StaticTrajectory",
    "SimulatedAntenna",
    "SimulatedCustomArray",
    "SimulatedAntennaArray",
    "SimulatedDipole",
    "SimulatedIdealAntenna",
    "SimulatedLinearAntenna",
    "SimulatedPatchAntenna",
    "SimulatedUniformArray",
    "Simulation",
    "DeviceFocus",
    "SimulatedDrop",
    "SidelobeEvaluator",
    "SI",
    "SSINR",
    "ADC",
    "DAC",
    "Gain",
    "AutomaticGainControl",
    "QuantizerType",
    "GainControlType",
    "PowerAmplifier",
    "SalehPowerAmplifier",
    "RappPowerAmplifier",
    "ClippingPowerAmplifier",
    "CustomPowerAmplifier",
    "HPF",
    "MixerType",
    "IdealMixer",
    "Mixer",
    "RampGenerator",
    "Shift",
    "Source",
    "Split",
    "Sum",
    "X4",
    "NoiseLevel",
    "N0",
    "ThermalNoise",
    "SNR",
    "NoiseModel",
    "NoiseRealization",
    "AWGN",
    "AWGNRealization",
    "PhaseNoise",
    "PhaseNoiseRealization",
    "NoPhaseNoise",
    "OscillatorPhaseNoise",
    "RFBlock",
    "RFBlockRealization",
    "RFBlockPort",
    "RFBlockPortType",
    "RFChain",
    "RFChainRealization",
    "RFBlockReference",
    "RFSignal",
    "SimulationScenario",
    "SimulatedDeviceState",
    "ProcessedSimulatedDeviceInput",
    "SimulatedDevice",
    "SimulatedDeviceOutput",
    "SimulatedDeviceReceiveRealization",
    "SimulatedDeviceTransmission",
    "SimulatedDeviceReception",
    "TriggerModel",
    "TriggerRealization",
    "RandomTrigger",
    "StaticTrigger",
    "SampleOffsetTrigger",
    "TimeOffsetTrigger",
    "isolation",
    "Isolation",
    "SpecificIsolation",
    "PerfectIsolation",
    "SelectiveLeakage",
    "Coupling",
    "ImpedanceCoupling",
    "PerfectCoupling",
    "SCIdealChannelEstimation",
    "SingleCarrierIdealChannelEstimation",
    "OFDMIdealChannelEstimation",
    "EBN0",
    "ESN0",
]
