# -*- coding: utf-8 -*-

from __future__ import annotations
from typing_extensions import override

import numpy as np
from matplotlib.axes import Axes
from matplotlib.figure import Figure

from hermespy.core import (
    ArtifactTemplate,
    DeserializationProcess,
    Evaluation,
    Hook,
    PlotVisualization,
    ScalarEvaluator,
    Serializable,
    SerializationProcess,
    VAT,
    ValueType,
)
from ..rf.block import ActiveRFBlock, RFBlock, RFBlockPropagation

__author__ = "Emre Can Ataş"
__copyright__ = "Copyright 2026, Barkhausen Institut gGmbH"
__credits__ = ["Emre Can Ataş"]
__license__ = "AGPLv3"
__version__ = "1.6.0"
__maintainer__ = "Jan Adler"
__email__ = "jan.adler@barkhauseninstitut.org"
__status__ = "Prototype"


class PowerConsumptionEvaluation(Evaluation[PlotVisualization]):
    """Efficiency of a single radio-frequency block during a single drop."""

    __input_power: np.ndarray
    __output_power: np.ndarray
    __dc_power: np.ndarray

    def __init__(
        self, input_power: np.ndarray, output_power: np.ndarray, dc_power: np.ndarray
    ) -> None:
        """
        Args:
            input_power: Instantaneous signal power at the block's input in Watt.
            output_power: Instantaneous signal power at the block's output in Watt.
            dc_power: Instantaneous direct current power drawn by the block in Watt.
        """

        self.__input_power = input_power
        self.__output_power = output_power
        self.__dc_power = dc_power

    @property
    def input_power(self) -> np.ndarray:
        """Instantaneous signal power at the block's input in Watt."""

        return self.__input_power

    @property
    def output_power(self) -> np.ndarray:
        """Instantaneous signal power at the block's output in Watt."""

        return self.__output_power

    @property
    def dc_power(self) -> np.ndarray:
        """Instantaneous direct current power drawn by the block in Watt."""

        return self.__dc_power

    @property
    def efficiency(self) -> float:
        """Average efficiency over the samples during which the block is driven.

        Computed as the mean of the per-sample ratio between the emitted signal power
        and the sum of supplied signal and direct current power. Samples during which
        neither the block's input nor its output carries any power are excluded from
        the average, so that the metric describes the block rather than the duty cycle
        of the processed signal.

        As a consequence, direct current power drawn while the block is idle is not
        reflected. For a duty-cycled signal such as the frames generated by
        :class:`RampGenerator<hermespy.simulation.rf.blocks.ramp.RampGenerator>`,
        this can amount to the majority of the consumed energy.
        """

        active = (self.__input_power > 0.0) | (self.__output_power > 0.0)

        if not np.any(active):
            return 0.0

        supplied = self.__input_power + self.__dc_power
        return float((self.__output_power[active] / supplied[active]).mean())

    @override
    def artifact(self) -> ArtifactTemplate[float]:
        return ArtifactTemplate(self.efficiency)

    @override
    def _prepare_visualization(
        self, figure: Figure | None, axes: VAT, **kwargs
    ) -> PlotVisualization:
        _ax: Axes = axes[0, 0]
        _ax.set_title("Block Power")
        _ax.set_ylabel("Power [W]")
        _ax.set_xlabel("Sample Index")

        lines = np.empty(axes.shape, dtype=object)
        lines[0, 0] = _ax.plot(self.__output_power, **kwargs)

        return PlotVisualization(figure, axes, lines)

    @override
    def _update_visualization(self, visualization: PlotVisualization, **kwargs) -> None:
        visualization.lines[0, 0][0].set_ydata(self.__output_power)


class PowerConsumptionEvaluator(ScalarEvaluator, Serializable):
    """Evaluate the total efficiency of a radio-frequency block.

    The efficiency is computed from the energy balance of the block,

    .. math::

        \\eta = \\frac{P_\\mathrm{out}}{P_\\mathrm{in} + P_\\mathrm{DC}} \\ \\text{,}

    where :math:`P_\\mathrm{DC}` is zero for
    :class:`PassiveRFBlock<hermespy.simulation.rf.block.PassiveRFBlock>`.
    """

    __block: RFBlock
    __propagate_hook: Hook[RFBlockPropagation]
    __propagation: RFBlockPropagation | None

    def __init__(
        self,
        block: RFBlock,
        confidence: float = 1.0,
        tolerance: float = 0.0,
        min_num_samples: int = 1024,
        plot_scale: str = "linear",
        tick_format: ValueType = ValueType.LIN,
        plot_surface: bool = True,
    ) -> None:
        """
        Args:
            block: The radio-frequency block to evaluate.
            confidence: Required confidence level for the given `tolerance` between zero and one.
            tolerance: Acceptable non-negative bound around the mean value of the estimated scalar performance indicator.
            min_num_samples: Minimum number of samples required to compute the confidence bound.
            plot_scale: Scale of the plot. Can be ``'linear'`` or ``'log'``.
            tick_format: Tick format of the plot.
            plot_surface: Enable surface plotting for two-dimensional grids. Enabled by default.
        """

        # Initialize the base class
        ScalarEvaluator.__init__(
            self, confidence, tolerance, min_num_samples, plot_scale, tick_format, plot_surface
        )

        self.__block = block
        self.__propagation = None
        self.__propagate_hook = block.add_propagate_callback(self.__propagate_callback)

    def __propagate_callback(self, propagation: RFBlockPropagation) -> None:
        """Callback function notifying the evaluator of a new propagation."""

        # Blocks on an inactive branch of the chain propagate empty signals
        if propagation.output.num_samples == 0:
            return

        self.__propagation = propagation

    @property
    def block(self) -> RFBlock:
        """The radio-frequency block being evaluated."""

        return self.__block

    @property
    @override
    def abbreviation(self) -> str:
        return "Eff"

    @property
    @override
    def title(self) -> str:
        return "Block Efficiency"

    @override
    def evaluate(self) -> PowerConsumptionEvaluation:
        if self.__propagation is None:
            raise RuntimeError(
                "Power consumption evaluator could not fetch a propagation. "
                "Has the block processed any signal?"
            )

        input_signal = self.__propagation.input.view(np.ndarray)
        output_signal = self.__propagation.output.view(np.ndarray)
        output_power = np.abs(output_signal) ** 2

        # Source blocks have no input ports, so no signal power is supplied to them
        if input_signal.shape[0] == 0:
            input_power = np.zeros(output_power.shape, dtype=np.float64)
            reference_signal = output_signal
        else:
            input_power = np.abs(input_signal) ** 2
            reference_signal = input_signal

        if isinstance(self.__block, ActiveRFBlock):
            dc_power = self.__block.dc_power_model.get_power(reference_signal)
        else:
            dc_power = np.zeros(output_power.shape, dtype=np.float64)

        return PowerConsumptionEvaluation(input_power, output_power, dc_power)

    def __del__(self) -> None:
        self.__propagate_hook.remove()

    @override
    def serialize(self, process: SerializationProcess) -> None:
        process.serialize_object(self.__block, "block")

    @classmethod
    @override
    def Deserialize(cls, process: DeserializationProcess) -> PowerConsumptionEvaluator:
        return cls(process.deserialize_object("block", RFBlock))


class DCPowerConsumptionEvaluation(PowerConsumptionEvaluation):
    """Direct current power drawn by a single radio-frequency block during a single drop.

    Reports the drawn power itself rather than the efficiency of its conversion.
    """

    @property
    def mean_dc_power(self) -> float:
        """Average direct current power drawn over the drop in Watt."""

        return float(np.mean(self.dc_power))

    @override
    def artifact(self) -> ArtifactTemplate[float]:
        return ArtifactTemplate(self.mean_dc_power)

    @override
    def _prepare_visualization(
        self, figure: Figure | None, axes: VAT, **kwargs
    ) -> PlotVisualization:
        _ax: Axes = axes[0, 0]
        _ax.set_title("Block Supply Power")
        _ax.set_ylabel("Power [W]")
        _ax.set_xlabel("Sample Index")

        lines = np.empty(axes.shape, dtype=object)
        lines[0, 0] = _ax.plot(self.dc_power, **kwargs)

        return PlotVisualization(figure, axes, lines)

    @override
    def _update_visualization(self, visualization: PlotVisualization, **kwargs) -> None:
        visualization.lines[0, 0][0].set_ydata(self.dc_power)


class DCPowerConsumptionEvaluator(PowerConsumptionEvaluator):
    """Evaluate the direct current power drawn by a radio-frequency block.

    Reports the average supply power of the block rather than its efficiency,

    .. math::

        P_\\mathrm{DC} = \\frac{1}{N} \\sum_{n} P_\\mathrm{DC}[n] \\ \\text{,}

    averaged over every sample of the propagation rather than only over the samples
    during which the block is driven, since the supply draw of an idle block is part
    of what the metric describes.

    Preferable to
    :class:`PowerConsumptionEvaluator<hermespy.simulation.evaluators.power.PowerConsumptionEvaluator>`
    wherever the efficiency is not a meaningful quantity. For a
    :class:`DAC<hermespy.simulation.rf.blocks.ad.DAC>` the block emits no radio-frequency
    signal whose power could be related to its supply, and for an
    :class:`ADC<hermespy.simulation.rf.blocks.ad.ADC>` quantization leaves the signal
    power almost unchanged, so that the efficiency approaches unity regardless of the
    configured resolution.
    """

    @property
    @override
    def abbreviation(self) -> str:
        return "P_DC"

    @property
    @override
    def title(self) -> str:
        return "Block Supply Power"

    @override
    def evaluate(self) -> DCPowerConsumptionEvaluation:
        evaluation = super().evaluate()

        return DCPowerConsumptionEvaluation(
            evaluation.input_power, evaluation.output_power, evaluation.dc_power
        )
