# -*- coding: utf-8 -*-

from .antennas import (
    Antenna,
    AntennaMode,
    AntennaPort,
    IdealAntenna,
    Dipole,
    LinearAntenna,
    PatchAntenna,
    AntennaArray,
    AntennaArrayState,
    CustomAntennaArray,
    UniformArray,
)
from .definitions import ConsoleMode, Verbosity
from .evaluators import (
    ReceivePowerEvaluator,
    PowerResult,
    PowerArtifact,
    PowerEvaluation,
    TransmitPowerEvaluator,
)
from .logarithmic import dB, Logarithmic, LogarithmicSequence, ValueType
from .operators import StaticOperator, SilentTransmitter, SignalTransmitter, SignalReceiver
from .channel import ChannelStateFormat, ChannelStateInformation, ChannelStateDimension
from .transformation import Direction, Transformable, TransformableBase, Transformation
from .device import (
    Operator,
    OperatorSlot,
    MixingOperator,
    ProcessedDeviceInput,
    TransmitterSlot,
    ReceiverSlot,
    Transmitter,
    Receiver,
    Device,
    FloatingError,
    Transmission,
    Reception,
    ReceptionType,
    DeviceReception,
    DeviceTransmission,
    DeviceInput,
    DeviceOutput,
)
from .executable import Executable
from .pipeline import Pipeline
from .factory import (
    Factory,
    Serializable,
    SerializableEnum,
    SerializationBackend,
    SerializationProcess,
    DeserializationProcess,
)
from .hooks import Hook, Hookable
from .monte_carlo import (
    Artifact,
    ArtifactTemplate,
    Evaluator,
    Evaluation,
    EvaluationResult,
    EvaluationTemplate,
    GridDimension,
    SamplePoint,
    ScalarDimension,
    ScalarEvaluationResult,
    MonteCarlo,
    MonteCarloActor,
    MonteCarloResult,
    MonteCarloSample,
    register,
)
from .precoding import (
    Precoder,
    Precoding,
    TransmitEncoder,
    TransmitPrecoding,
    TransmitSignalCoding,
    TransmitStreamEncoder,
    ReceiveDecoder,
    ReceivePrecoding,
    ReceiveSignalCoding,
    ReceiveStreamDecoder,
)
from .state import State, DeviceState, DST, TransmitState, ReceiveState
from .random_node import RandomRealization, RandomNode
from .drop import Drop
from .scenario import Scenario, ScenarioMode, ScenarioType, ReplayScenario
from .signal_model import Signal, SignalBlock, DenseSignal, SparseSignal
from .visualize import (
    ScatterVisualization,
    PlotVisualization,
    StemVisualization,
    ImageVisualization,
    QuadMeshVisualization,
    VAT,
    Visualization,
    VLT,
    Visualizable,
    VisualizableAttribute,
    VT,
)

__author__ = "André Noll Barreto"
__copyright__ = "Copyright 2024, Barkhausen Institut gGmbH"
__credits__ = ["André Barreto", "Jan Adler"]
__license__ = "AGPLv3"
__version__ = "1.4.0"
__maintainer__ = "Jan Adler"
__email__ = "jan.adler@barkhauseninstitut.org"
__status__ = "Prototype"


__all__ = [
    "Antenna",
    "AntennaMode",
    "AntennaPort",
    "IdealAntenna",
    "Dipole",
    "LinearAntenna",
    "PatchAntenna",
    "AntennaArray",
    "AntennaArrayState",
    "CustomAntennaArray",
    "UniformArray",
    "SNRType",
    "ReceivePowerEvaluator",
    "PowerResult",
    "PowerArtifact",
    "PowerEvaluation",
    "TransmitPowerEvaluator",
    "dB",
    "Logarithmic",
    "LogarithmicSequence",
    "ValueType",
    "StaticOperator",
    "SilentTransmitter",
    "SignalTransmitter",
    "SignalReceiver",
    "ChannelStateFormat",
    "ChannelStateInformation",
    "ChannelStateDimension",
    "Direction",
    "Transformable",
    "TransformableBase",
    "Transformation",
    "Operator",
    "OperatorSlot",
    "MixingOperator",
    "TransmitterSlot",
    "ReceiverSlot",
    "Transmitter",
    "Receiver",
    "Device",
    "FloatingError",
    "Transmission",
    "Reception",
    "ReceptionType",
    "DeviceInput",
    "DeviceOutput",
    "DeviceReception",
    "DeviceTransmission",
    "Executable",
    "Verbosity",
    "Pipeline",
    "Hook",
    "Hookable",
    "Artifact",
    "ArtifactTemplate",
    "ConsoleMode",
    "Evaluator",
    "Evaluator",
    "Evaluation",
    "EvaluationResult",
    "EvaluationTemplate",
    "GridDimension",
    "SamplePoint",
    "ScalarDimension",
    "ScalarEvaluationResult",
    "MonteCarlo",
    "MonteCarloActor",
    "MonteCarloResult",
    "MonteCarloSample",
    "register",
    "Factory",
    "Serializable",
    "SerializableEnum",
    "SerializationBackend",
    "SerializationProcess",
    "DeserializationProcess",
    "Precoder",
    "Precoding",
    "TransmitEncoder",
    "TransmitPrecoding",
    "TransmitSignalCoding",
    "TransmitStreamEncoder",
    "ReceiveDecoder",
    "ReceivePrecoding",
    "ReceiveSignalCoding",
    "ReceiveStreamDecoder",
    "State",
    "DeviceState",
    "DST",
    "TransmitState",
    "ReceiveState",
    "RandomRealization",
    "RandomNode",
    "Drop",
    "Scenario",
    "ScenarioMode",
    "ScenarioType",
    "ReplayScenario",
    "Signal",
    "SignalBlock",
    "DenseSignal",
    "SparseSignal",
    "ProcessedDeviceInput",
    "DeviceInput",
    "ScatterVisualization",
    "PlotVisualization",
    "StemVisualization",
    "ImageVisualization",
    "QuadMeshVisualization",
    "VAT",
    "Visualization",
    "VLT",
    "Plot",
    "Visualizable",
    "VisualizableAttribute",
    "VT",
]
