name: hermespy

# Execute tests if pushed to any branch
on: [push, pull_request]

jobs:
  documentation:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        lfs: false

    - name: Setup python 3.7.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7.7

    - name: Install doc dependencies
      run: |
        pip install -r requirements.txt
        pip install -r requirements_doc.txt

    - name: Build documentation
      run: cd docssource && make api && make gh-pages && make install

    - name: Create github pages
      uses: JamesIves/github-pages-deploy-action@4.1.2
      with:
        branch: gh-pages
        folder: docs

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo + lfs
      uses: actions/checkout@v2
      with:
        lfs: true

    - name: Set up Python 3.7.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7.7

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install .

    - name: Run unit tests
      run: python run_unit_tests.py

  dist:
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        runs-on: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout repo + lfs
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Build SDist and wheel
      run: pipx run build

    - uses: actions/upload-artifact@v2
      with:
        path: dist/*

    - name: Check metadata
      run: pipx run twine check dist/*