name: hermespy

# Execute tests if pushed to any branch
on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install git lfs
      run: sudo apt-get update && sudo apt-get install -y git-lfs && sudo git lfs install
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test without using pytest
      run: |
        python run_unit_tests.py
