name: hermespy

# Execute tests if pushed to any branch
on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo + lfs
      uses: actions/checkout@v2
      with:
        lfs: true
    - name: Set up Python 3.7.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f requirements_doc.txt ]; then pip install -r requirements_doc.txt; fi
    - name: Build documentation
      run: cd docssource && make gh-pages && make copy
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.2
      with:
        branch: gh-pages
        folder: docs
    - name: Test
      run: python run_unit_tests.py
