name: Publish Documentation

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

env:
  HERMES_QUADRIGA: ${{ github.workspace }}/submodules/quadriga/quadriga_src

jobs:

  Documentation-Release:
  
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        lfs: true
        submodules: recursive

    - name: Setup python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install doc dependencies
      run: |
        sudo apt update
        sudo apt-get install -y build-essential octave portaudio19-dev python-dev-is-python3 pandoc graphviz
        export MAKEFLAGS="-j $(grep -c ^processor /proc/cpuinfo)"
        pip install -e .[test,documentation,quadriga,uhd,audio,scapy,sionna]

    - name: Build documentation
      run: sphinx-build docssource/ documentation/

    # ToDo: Execute this action only on the highest tag
    - name: Create github pages
      uses: JamesIves/github-pages-deploy-action@4.1.2
      with:
        branch: gh-pages
        folder: documentation
